# Generated by Django 2.2.28 on 2024-09-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('phone_numer', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerList',
            fields=[
                ('game_week', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(to='players.Players')),
            ],
        ),
    ]
