# Generated by Django 2.2.28 on 2024-09-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name_plural': 'Players'},
        ),
        migrations.RenameField(
            model_name='players',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
